champName = ["Aatrox","Ahri","Akali","Alistar","Amumu","Anivia",
             "Annie","Ashe","AurelionSol","Azir","Bard","Blitzcrank",
             "Brand","Braum","Caitlyn","Camille","Cassiopeia","ChoGath",
             "Corki","Darius","Diana","DrMundo","Draven","Ekko",
             "Elise","Evelynn","Ezreal","Fiddlesticks","Fiora","Fizz",
             "Galio","Gangplank","Garen","Gnar","Gragas","Graves",
             "Hecarim","Heimerdinger","Illaoi","Irelia","Ivern","Janna",
             "JarvanIV","Jax","Jayce","Jhin","Jinx","KaiSa",
             "Kalista","Karma","Karthus","Kassadin","Katarina","Kayle",
             "Kayn","Kennen","KhaZix","Kindred","Kled","KogMaw",
             "LeBlanc","LeeSin","Leona","Lissandra","Lucian","Lulu",
             "Lux","Malphite","Malzahar","Maokai","MasterYi","MissFortune",
             "Mordekaiser","Morgana","Nami","Nasus","Nautilus",
             "Nidalee","Nocturne","NunuWillump","Olaf","Orianna","Ornn",
             "Pantheon","Poppy","Pyke","Quinn","Rakan", "Rammus",
             "RekSai","Renekton","Rengar","Riven","Rumble","Ryze",
             "Sejuani","Shaco","Shen","Shyvana","Singed","Sion",
             "Sivir","Skarner","Sona","Soraka","Swain","Syndra",
             "TahmKench","Taliyah","Talon","Taric","Teemo","Thresh",
             "Tristana","Trundle","Tryndamere","TwistedFate","Twitch","Udyr",
             "Urgot","Varus","Vayne","Veigar","VelKoz","Vi","Viktor",
             "Vladimir","Volibear","Warwick","Wukong","Xayah","Xerath",
             "XinZhao","Yasuo","Yorick","Zac","Zed","Ziggs",
             "Zilean","Zoe","Zyra"]


def ChNameToID(name):
    return {'aatrox': '266', 'thresh': '412', 'tryndamere': '23', 'gragas': '79',
            'cassiopeia': '69', 'aurelionsol': '136', 'ryze': '13', 'poppy': '78',
            'sion': '14', 'annie': '1', 'jhin': '202', 'karma': '43',
            'nautilus': '111', 'kled': '240', 'lux': '99', 'ahri': '103',
            'olaf': '2', 'viktor': '112', 'anivia': '34', 'singed': '27',
            'garen': '86', 'lissandra': '127', 'maokai': '57', 'morgana': '25',
            'evelynn': '28', 'fizz': '105', 'heimerdinger': '74', 'zed': '238',
            'rumble': '68', 'mordekaiser': '82', 'sona': '37', 'kogmaw': '96',
            'zoe': '142', 'katarina': '55', 'lulu': '117', 'ashe': '22',
            'karthus': '30', 'alistar': '12', 'xayah': '498', 'darius': '122',
            'rakan': '497', 'vayne': '67', 'varus': '110', 'pyke': '555',
            'udyr': '77', 'leona': '89', 'ornn': '516', 'jayce': '126',
            'syndra': '134', 'pantheon': '80', 'riven': '92', 'khazix': '121',
            'corki': '42', 'azir': '268', 'caitlyn': '51', 'nidalee': '76',
            'kennen': '85', 'kayn': '141', 'galio': '3', 'veigar': '45',
            'bard': '432', 'gnar': '150', 'kaisa': '145', 'malzahar': '90',
            'graves': '104', 'vi': '254', 'kayle': '10', 'irelia': '39',
            'leesin': '64', 'camille': '164', 'illaoi': '420', 'elise': '60',
            'volibear': '106', 'nunuwillump': '20', 'twistedfate': '4', 'jax': '24',
            'shyvana': '102', 'kalista': '429', 'drmundo': '36', 'ivern': '427',
            'diana': '131', 'tahmkench': '223', 'brand': '63', 'sejuani': '113',
            'vladimir': '8', 'zac': '154', 'reksai': '421', 'quinn': '133',
            'akali': '84', 'taliyah': '163', 'tristana': '18', 'hecarim': '120',
            'sivir': '15', 'lucian': '236', 'rengar': '107', 'warwick': '19',
            'skarner': '72', 'malphite': '54', 'yasuo': '157', 'xerath': '101',
            'teemo': '17', 'nasus': '75', 'renekton': '58', 'draven': '119',
            'shaco': '35', 'swain': '50', 'talon': '91', 'janna': '40',
            'ziggs': '115', 'ekko': '245', 'orianna': '61', 'fiora': '114',
            'fiddlesticks': '9', 'chogath': '31', 'rammus': '33', 'leblanc': '7',
            'ezreal': '81', 'jarvaniv': '59', 'nami': '267', 'zyra': '143',
            'velkoz': '161', 'kassadin': '38', 'trundle': '48', 'gangplank': '41',
            'amumu': '32', 'taric': '44', 'masteryi': '11', 'twitch': '29',
            'xinzhao': '5', 'braum': '201', 'shen': '98', 'blitzcrank': '53',
            'wukong': '62', 'missfortune': '21', 'kindred': '203', 'urgot': '6',
            'yorick': '83', 'jinx': '222', 'nocturne': '56', 'zilean': '26',
            'soraka': '16'
            }.get(name,'-1')
